name: dsprac

dependencies:
  - python=3.7.9
  - anaconda 
  - pip 
  - pandas=1.1.5  # same as Colab
  - matplotlib=3.2.2  # same as Colab
  - bokeh=2.1.1 # same as Colab
  - conda-forge::jupyter_contrib_nbextensions
  - pip:
    - missingno==0.4.2  # same as Colab
    - seaborn==0.11.1 # same as Colab
